---
# centos 7 only !
- hosts: localhost
  tasks:
  - name: Begin
    debug:
      msg: Start mail system configuration
  - name: Load variables
    import_tasks: mail/vars/vars.yml
  - name: Load installation tasks
    import_tasks: mail/install/install.yml
  - name: Load configuration tasks
    import_tasks: mail/config/configure.yml
  - name: Debug
    debug:
      msg: Good !
    tags:
      - dbg
